### ISSUE TITLE
Running the server with "th server.lua" doesn’t work.

### ISSUE THREAD

**Issue by sarahmautsch** [robinsloan/torch-rnn-server#2]
Hey, I installed everything but when I try to run th server.lua I get the following error:

`module 'cutorch' not found:No LuaRocks module found for cutorch`

Any ideas?

**Comment by robinsloan** [comment]
Hi @sarahmautsch! Try running this command:

```
th server.lua -gpu -1
```

If that works, we'll know the problem is GPU support -- which is what I suspect. I tore the OpenCL bindings out of `server.lua` so that might be the problem, depending on your system -- but before we proceed down that path, let me know if the above command works for you.

**Comment by mcwhittemore** [comment]
I had this same problem and running without a gpu this way seems to work.

**Comment by robinsloan** [comment]
@mcwhittemore, what computer & operating system are you running on?

**Comment by mcwhittemore** [comment]
@robinsloan, I'm on a mac running OSX El Capitan. I don't have an nvida graphics card so I have to use my cpu. I'm working on getting the opencl version of torch-rnn working as I think this solves that...? Once I do, I'll open a PR for the torch-rnn-server to work with opencl.

**Comment by robinsloan** [comment]
Sounds great, @mcwhittemore. I ripped out all the OpenCL code (before I knew I would post this project publicly) so if you can get `torch-rnn` running it should be a snap to add it back.
